### ISSUE TITLE
File download doesn't work

### ISSUE THREAD

**Issue by chriscoomber** [zalando/connexion#203]
I'm trying to use connexion to return a requested file, such that the 200 response has a binary string as its body. I've tried two ways so far and neither have worked. The first looks like a bug in swagger_spec_validator, but the second looks like a Connexion issue.

Swagger yaml fragment:
```
  /deployments/{deployment_id}/avatars/{avatar_filename}:
    get:
      tags:
      - "Avatars"
      summary: "Download an avatar"
      operationId: "mypackage.controller.get_avatar"
      produces:
      - "application/octet-stream"
      parameters:
      - $ref: "#/parameters/deployment_id"
      - $ref: "#/parameters/avatar_filename"
      responses:
        200:
          description: Avatar file
          # Choose one of the schema's below
          # Problem 1 occurs if schema has type: file
          schema:
            type: file
          # Problem 2 occurs if schema has type: string
          schema:
            type: string
            format: binary
        201:
          description: "Avatar uploaded"
```

### Problem 1
I raised https://github.com/Yelp/swagger_spec_validator/issues/46 to cover this, but actually this is fixed in latest master. Essentially swagger_spec_validator didn't like the "file" type in a response schema.

### Problem 2
To work around problem 1, we instead try to return a binary string (octet-stream). My handler code is:
```
def get_avatar(deployment_id, avatar_filename):
    avatar_path = os.path.join(settings.AVATAR_DIR, avatar_filename)

    with open(avatar_path, 'r') as f:
        return f.read()
```
This string clearly isn't necessarily utf-8 encoded (it's the contents of a binary file), but Connexion assumes it is at https://github.com/zalando/connexion/blob/master/connexion/decorators/response.py#L57, when it tries to encode it as JSON.
Full error:
```
Traceback (most recent call last):
  File "myeggsdir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "myeggsdir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "myeggsdir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "myeggsdir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "myeggsdir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "myeggsdir/eggs/connexion-1.0.84-py2.7.egg/connexion/decorators/validation.py", line 245, in wrapper
    response = function(*args, **kwargs)
  File "myeggsdir/eggs/connexion-1.0.84-py2.7.egg/connexion/decorators/produces.py", line 85, in wrapper
    data, status_code, headers = self.get_full_response(function(*args, **kwargs))
  File "myeggsdir/eggs/connexion-1.0.84-py2.7.egg/connexion/decorators/response.py", line 82, in wrapper
    self.validate_response(data, status_code, headers)
  File "myeggsdir/eggs/connexion-1.0.84-py2.7.egg/connexion/decorators/response.py", line 57, in validate_response
    data = json.dumps(data)
  File "myeggsdir/eggs/Flask-0.10.1-py2.7.egg/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    return encode_basestring_ascii(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 4050: invalid start byte
```
It seems like the only solution is to base-64 encode my file before sending, which I shouldn't have to do.

**Comment by dimbleby** [comment]
I think that the first issue above was fixed only last week, via Yelp/swagger_spec_validator#40.  (This is not yet published).

**Comment by chriscoomber** [comment]
I've double checked the issue I raised (https://github.com/Yelp/swagger_spec_validator/issues/46) on their master branch and it still fails, so I'm not sure.

**Comment by rafaelcaricio** [comment]
@dimbleby @chriscoomber I made some changes in Connexion to behave properly when the operations return binary data. It should help you here.
